### ISSUE TITLE
Half-Life 2 Deathmatch crashing on startup

### ISSUE THREAD

**Issue by Derik555** [taiyungwang/hl2_goap_bot#2]
I installed the mod as instructed, dropped the contents into my hl2mp folder and added -insecure to the starting options which causes me to get to the intro video of the game and then the game closes itself.

Also this seems like an extremely interesting project, id love it if you could revamp css and if possible tf2 bots

**Comment by Derik555** [comment]
Still experiencing the same crash on the latest version, perhaps i need an older version of hl2dm?

**Comment by taiyungwang** [comment]
v1.1.5 should fix the crash you're experiencing.

**Comment by Derik555** [comment]
Works perfectly now, thank you for the swift response. All in all i gotta say this is an amazing concept with so much room to grow, i really hope this project takes off ithe near future.
